version: "3.5"

services:
  chef-workstation:
    container_name: chef-workstation
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CODE_VERSION: 18.04
        BASE_DISTRO: ubuntu
    ports:
      - 443:443
    networks:
      - mitlabs
    restart: always
    stdin_open: true
    tty: true
networks:
  mitlabs:
    name: mitlabs
    driver: bridge
